CREATE SCHEMA  IF NOT EXISTS `menu_schema`;


CREATE TABLE RECIPE(
ID VARCHAR(36) PRIMARY KEY default UUID(),
DESCRIPTION VARCHAR(36) default NULL,
COOK_TIME SMALLINT(3) DEFAULT NULL
);

-- only upper case data in this table
CREATE TABLE QUANTITY_TYPE(
	ID VARCHAR(36) PRIMARY KEY,
	CONSTRAINT upper_case_quantity_type CHECK( STRCMP(UPPER(ID),ID) = 0)
);

-- only upper case data in this table
CREATE TABLE INGREDIENT(
	ID VARCHAR(36) PRIMARY KEY,
	QUANTITY_TYPE_ID VARCHAR(20) NOT NULL,
	CONSTRAINT FK_INGREDIENT_QUANTITY_TYPE FOREIGN KEY (QUANTITY_TYPE_ID) REFERENCES QUANTITY_TYPE(ID) ON DELETE CASCADE,
	CONSTRAINT upper_case_ingredient CHECK(STRCMP(UPPER(ID),ID) = 0)
);
