CREATE SCHEMA  IF NOT EXISTS `menu_schema`;

CREATE TABLE menu_schema.RECIPE(
ID VARCHAR(36) PRIMARY KEY default UUID(),
DESCRIPTION VARCHAR(150) default NULL,
COOK_TIME SMALLINT(3) DEFAULT NULL
);

-- only upper case data in this table
CREATE TABLE menu_schema.QUANTITY_TYPE(
	ID VARCHAR(36) PRIMARY KEY,
	CONSTRAINT upper_case_quantity_type CHECK( STRCMP(UPPER(ID),ID) = 0)
);

-- only upper case data in this table
CREATE TABLE menu_schema.ingredient(
	ID VARCHAR(36) PRIMARY KEY,
	QUANTITY_TYPE_ID VARCHAR(20) NOT NULL,
	CONSTRAINT FK_INGREDIENT_QUANTITY_TYPE FOREIGN KEY (QUANTITY_TYPE_ID) REFERENCES QUANTITY_TYPE(ID) ON DELETE CASCADE,
	CONSTRAINT upper_case_ingredient CHECK(STRCMP(UPPER(ID),ID) = 0)
);

CREATE TABLE menu_schema.MENU_TYPE (
	ID VARCHAR(36) PRIMARY KEY,
	DESCRIPTION VARCHAR(50)
);

CREATE TABLE menu_schema.RECIPE_INGREDIENT(
	RECIPE_ID VARCHAR(36),
	INGREDIENT_ID VARCHAR(36),
	QUANTITY DECIMAL(10,2) NOT NULL,
	UNIQUE KEY RECIPE_INGREDIENT_ID (RECIPE_ID,INGREDIENT_ID),
	CONSTRAINT FK_RECIPE_INGREDIENT_INGREDIENT FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(ID) ON DELETE CASCADE,
	CONSTRAINT FK_RECIPE_INGREDIENT_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(ID) ON DELETE CASCADE
);